//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVRTK.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HardwareInputPrompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HardwareInputPrompts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BVRTK.Resources.HardwareInputPrompts", typeof(HardwareInputPrompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord.
        /// </summary>
        internal static string Chord {
            get {
                return ResourceManager.GetString("Chord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Button East.
        /// </summary>
        internal static string FaceButtonEast {
            get {
                return ResourceManager.GetString("FaceButtonEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Button North.
        /// </summary>
        internal static string FaceButtonNorth {
            get {
                return ResourceManager.GetString("FaceButtonNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Button South.
        /// </summary>
        internal static string FaceButtonSouth {
            get {
                return ResourceManager.GetString("FaceButtonSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Button West.
        /// </summary>
        internal static string FaceButtonWest {
            get {
                return ResourceManager.GetString("FaceButtonWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grip Button.
        /// </summary>
        internal static string GripButton {
            get {
                return ResourceManager.GetString("GripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grip Trigger.
        /// </summary>
        internal static string GripTrigger {
            get {
                return ResourceManager.GetString("GripTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Held.
        /// </summary>
        internal static string KeyTriggerHeld {
            get {
                return ResourceManager.GetString("KeyTriggerHeld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        internal static string KeyTriggerPress {
            get {
                return ResourceManager.GetString("KeyTriggerPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string KeyTriggerRelease {
            get {
                return ResourceManager.GetString("KeyTriggerRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string KeyTriggerRepeat {
            get {
                return ResourceManager.GetString("KeyTriggerRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button.
        /// </summary>
        internal static string OtherButton {
            get {
                return ResourceManager.GetString("OtherButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick Button.
        /// </summary>
        internal static string StickButton {
            get {
                return ResourceManager.GetString("StickButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick East.
        /// </summary>
        internal static string StickEast {
            get {
                return ResourceManager.GetString("StickEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick North.
        /// </summary>
        internal static string StickNorth {
            get {
                return ResourceManager.GetString("StickNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick South.
        /// </summary>
        internal static string StickSouth {
            get {
                return ResourceManager.GetString("StickSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick West.
        /// </summary>
        internal static string StickWest {
            get {
                return ResourceManager.GetString("StickWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Button North.
        /// </summary>
        internal static string SystemButtonNorth {
            get {
                return ResourceManager.GetString("SystemButtonNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Button South.
        /// </summary>
        internal static string SystemButtonSouth {
            get {
                return ResourceManager.GetString("SystemButtonSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tackpad Center.
        /// </summary>
        internal static string TrackpadCenter {
            get {
                return ResourceManager.GetString("TrackpadCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackpad East.
        /// </summary>
        internal static string TrackpadEast {
            get {
                return ResourceManager.GetString("TrackpadEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackpad North.
        /// </summary>
        internal static string TrackpadNorth {
            get {
                return ResourceManager.GetString("TrackpadNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackpad South.
        /// </summary>
        internal static string TrackpadSouth {
            get {
                return ResourceManager.GetString("TrackpadSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackpad West.
        /// </summary>
        internal static string TrackpadWest {
            get {
                return ResourceManager.GetString("TrackpadWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Primary.
        /// </summary>
        internal static string TriggerPrimary {
            get {
                return ResourceManager.GetString("TriggerPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Secondary.
        /// </summary>
        internal static string TriggerSecondary {
            get {
                return ResourceManager.GetString("TriggerSecondary", resourceCulture);
            }
        }
    }
}
