//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BVRTK.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HardwareInputPrompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HardwareInputPrompts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BVRTK.Resources.HardwareInputPrompts", typeof(HardwareInputPrompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 1.
        /// </summary>
        internal static string Chord1 {
            get {
                return ResourceManager.GetString("Chord1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 10.
        /// </summary>
        internal static string Chord10 {
            get {
                return ResourceManager.GetString("Chord10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 11.
        /// </summary>
        internal static string Chord11 {
            get {
                return ResourceManager.GetString("Chord11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 12.
        /// </summary>
        internal static string Chord12 {
            get {
                return ResourceManager.GetString("Chord12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 13.
        /// </summary>
        internal static string Chord13 {
            get {
                return ResourceManager.GetString("Chord13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 14.
        /// </summary>
        internal static string Chord14 {
            get {
                return ResourceManager.GetString("Chord14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 15.
        /// </summary>
        internal static string Chord15 {
            get {
                return ResourceManager.GetString("Chord15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 16.
        /// </summary>
        internal static string Chord16 {
            get {
                return ResourceManager.GetString("Chord16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 2.
        /// </summary>
        internal static string Chord2 {
            get {
                return ResourceManager.GetString("Chord2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 3.
        /// </summary>
        internal static string Chord3 {
            get {
                return ResourceManager.GetString("Chord3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 4.
        /// </summary>
        internal static string Chord4 {
            get {
                return ResourceManager.GetString("Chord4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 5.
        /// </summary>
        internal static string Chord5 {
            get {
                return ResourceManager.GetString("Chord5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 6.
        /// </summary>
        internal static string Chord6 {
            get {
                return ResourceManager.GetString("Chord6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 7.
        /// </summary>
        internal static string Chord7 {
            get {
                return ResourceManager.GetString("Chord7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 8.
        /// </summary>
        internal static string Chord8 {
            get {
                return ResourceManager.GetString("Chord8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chord 9.
        /// </summary>
        internal static string Chord9 {
            get {
                return ResourceManager.GetString("Chord9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Button East.
        /// </summary>
        internal static string FaceButtonEast {
            get {
                return ResourceManager.GetString("FaceButtonEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Button North.
        /// </summary>
        internal static string FaceButtonNorth {
            get {
                return ResourceManager.GetString("FaceButtonNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Button South.
        /// </summary>
        internal static string FaceButtonSouth {
            get {
                return ResourceManager.GetString("FaceButtonSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Button West.
        /// </summary>
        internal static string FaceButtonWest {
            get {
                return ResourceManager.GetString("FaceButtonWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grip Button.
        /// </summary>
        internal static string GripButton {
            get {
                return ResourceManager.GetString("GripButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grip Trigger.
        /// </summary>
        internal static string GripTrigger {
            get {
                return ResourceManager.GetString("GripTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 1.
        /// </summary>
        internal static string OtherButton1 {
            get {
                return ResourceManager.GetString("OtherButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 10.
        /// </summary>
        internal static string OtherButton10 {
            get {
                return ResourceManager.GetString("OtherButton10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 11.
        /// </summary>
        internal static string OtherButton11 {
            get {
                return ResourceManager.GetString("OtherButton11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 12.
        /// </summary>
        internal static string OtherButton12 {
            get {
                return ResourceManager.GetString("OtherButton12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 13.
        /// </summary>
        internal static string OtherButton13 {
            get {
                return ResourceManager.GetString("OtherButton13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 14.
        /// </summary>
        internal static string OtherButton14 {
            get {
                return ResourceManager.GetString("OtherButton14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 15.
        /// </summary>
        internal static string OtherButton15 {
            get {
                return ResourceManager.GetString("OtherButton15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 16.
        /// </summary>
        internal static string OtherButton16 {
            get {
                return ResourceManager.GetString("OtherButton16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 2.
        /// </summary>
        internal static string OtherButton2 {
            get {
                return ResourceManager.GetString("OtherButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 3.
        /// </summary>
        internal static string OtherButton3 {
            get {
                return ResourceManager.GetString("OtherButton3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 4.
        /// </summary>
        internal static string OtherButton4 {
            get {
                return ResourceManager.GetString("OtherButton4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 5.
        /// </summary>
        internal static string OtherButton5 {
            get {
                return ResourceManager.GetString("OtherButton5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 6.
        /// </summary>
        internal static string OtherButton6 {
            get {
                return ResourceManager.GetString("OtherButton6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 7.
        /// </summary>
        internal static string OtherButton7 {
            get {
                return ResourceManager.GetString("OtherButton7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 8.
        /// </summary>
        internal static string OtherButton8 {
            get {
                return ResourceManager.GetString("OtherButton8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Button 9.
        /// </summary>
        internal static string OtherButton9 {
            get {
                return ResourceManager.GetString("OtherButton9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick Button.
        /// </summary>
        internal static string StickButton {
            get {
                return ResourceManager.GetString("StickButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick East.
        /// </summary>
        internal static string StickEast {
            get {
                return ResourceManager.GetString("StickEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick North.
        /// </summary>
        internal static string StickNorth {
            get {
                return ResourceManager.GetString("StickNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick South.
        /// </summary>
        internal static string StickSouth {
            get {
                return ResourceManager.GetString("StickSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stick West.
        /// </summary>
        internal static string StickWest {
            get {
                return ResourceManager.GetString("StickWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Button North.
        /// </summary>
        internal static string SystemButtonNorth {
            get {
                return ResourceManager.GetString("SystemButtonNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Button South.
        /// </summary>
        internal static string SystemButtonSouth {
            get {
                return ResourceManager.GetString("SystemButtonSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tackpad Button.
        /// </summary>
        internal static string TrackpadButton {
            get {
                return ResourceManager.GetString("TrackpadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackpad East.
        /// </summary>
        internal static string TrackpadEast {
            get {
                return ResourceManager.GetString("TrackpadEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackpad North.
        /// </summary>
        internal static string TrackpadNorth {
            get {
                return ResourceManager.GetString("TrackpadNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackpad South.
        /// </summary>
        internal static string TrackpadSouth {
            get {
                return ResourceManager.GetString("TrackpadSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trackpad West.
        /// </summary>
        internal static string TrackpadWest {
            get {
                return ResourceManager.GetString("TrackpadWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Primary.
        /// </summary>
        internal static string TriggerPrimary {
            get {
                return ResourceManager.GetString("TriggerPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Secondary.
        /// </summary>
        internal static string TriggerSecondary {
            get {
                return ResourceManager.GetString("TriggerSecondary", resourceCulture);
            }
        }
    }
}
